var hora = new Date()
var minut = new Date()
var secon = new Date()
var dia = new Date()
var mes = new Date()
var ano = new Date()
var h_agora = hora.getHours()
var m_agora = minut.getMinutes()
var s_agora = secon.getSeconds()
var d_agora = dia.getDate()
var me_agora = mes.getMonth() + 1
var a_agora = ano.getFullYear()
console.log(`Agora são ${h_agora}:${m_agora}:${s_agora} da data de ${d_agora}/${me_agora}/${a_agora}`)